"""Comprehensive agronomic crop database for AgriAssist.
Contains detailed climate, soil, nutrient, and management guidelines for 28+ crops.
"""

from typing import List, Dict, Any

CROPS_DATABASE: List[Dict[str, Any]] = [
    # ------------------ CEREALS ------------------
    {
        "id": "rice",
        "name": "Rice (Paddy)",
        "hindi_name": "धान (Chawal)",
        "scientific_name": "Oryza sativa",
        "category": "Cereal",
        "suitable_soils": ["Clay Loam Soil", "Alluvial Soil"],
        "tolerated_soils": ["Red Soil"],
        "min_ph": 5.0,
        "max_ph": 8.0,
        "optimal_ph_min": 6.0,
        "optimal_ph_max": 7.5,
        "min_temp": 20.0,
        "max_temp": 38.0,
        "optimal_temp_min": 22.0,
        "optimal_temp_max": 32.0,
        "min_rainfall": 900.0,
        "max_rainfall": 2500.0,
        "water_requirement": "High",
        "seasons": ["Kharif", "Zaid"],
        "sowing_window": "June - July (Kharif) or Jan - Feb (Boro/Zaid)",
        "duration_days": "115 - 145 days",
        "estimated_yield_per_acre": "22 - 28 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "Moderate to High",
        "ideal_n": 100.0,
        "ideal_p": 50.0,
        "ideal_k": 50.0,
        "sowing_tips": "Treat seeds with Carbendazim (2g/kg). Maintain 2-3 cm standing water during transplanting and tillering.",
        "fertilizer_advice": "Apply 50% N + full P & K as basal dose; top dress remaining N in 2 equal splits at tillering and panicle initiation.",
        "soil_notes": "Needs soil with high water holding capacity and slow percolation like clay loams.",
        "risk_factors": ["Blast disease", "Stem borer", "Severe drought during panicle stage"],
        "companion_crops": ["Azolla biofertilizer", "Fish-rice culture", "Border marigolds"]
    },
    {
        "id": "wheat",
        "name": "Wheat",
        "hindi_name": "गेहूं (Gehun)",
        "scientific_name": "Triticum aestivum",
        "category": "Cereal",
        "suitable_soils": ["Alluvial Soil", "Clay Loam Soil", "Black Soil (Regur)"],
        "tolerated_soils": ["Sandy Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 8.2,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 12.0,
        "max_temp": 28.0,
        "optimal_temp_min": 15.0,
        "optimal_temp_max": 24.0,
        "min_rainfall": 300.0,
        "max_rainfall": 800.0,
        "water_requirement": "Medium",
        "seasons": ["Rabi"],
        "sowing_window": "November 1st - November 25th (ideal window)",
        "duration_days": "110 - 130 days",
        "estimated_yield_per_acre": "18 - 24 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "Moderate",
        "ideal_n": 120.0,
        "ideal_p": 60.0,
        "ideal_k": 40.0,
        "sowing_tips": "Use seed drill for uniform 4-5 cm depth. First irrigation (CRI stage at 21 days) is critical.",
        "fertilizer_advice": "Half N with full P and K at sowing; remaining half N at 1st irrigation (CRI stage).",
        "soil_notes": "Prefers well-drained fertile loam; waterlogging harms root respiration.",
        "risk_factors": ["Terminal heat stress during grain filling", "Yellow rust", "Late sowing yield drop"],
        "companion_crops": ["Mustard (intercropped 9:1 ratio)", "Chickpea"]
    },
    {
        "id": "maize",
        "name": "Maize (Corn)",
        "hindi_name": "मक्का (Makka)",
        "scientific_name": "Zea mays",
        "category": "Cereal",
        "suitable_soils": ["Alluvial Soil", "Red Soil", "Sandy Loam Soil", "Black Soil (Regur)"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 5.8,
        "max_ph": 7.8,
        "optimal_ph_min": 6.2,
        "optimal_ph_max": 7.2,
        "min_temp": 18.0,
        "max_temp": 35.0,
        "optimal_temp_min": 21.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 450.0,
        "max_rainfall": 950.0,
        "water_requirement": "Medium",
        "seasons": ["Kharif", "Rabi", "Zaid"],
        "sowing_window": "June - July (Kharif) or Oct - Nov (Rabi)",
        "duration_days": "85 - 110 days",
        "estimated_yield_per_acre": "24 - 32 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "High",
        "ideal_n": 120.0,
        "ideal_p": 60.0,
        "ideal_k": 40.0,
        "sowing_tips": "Maintain 60cm row-to-row and 20cm plant-to-plant spacing. Avoid waterlogging during initial 30 days.",
        "fertilizer_advice": "Apply zinc sulfate @ 10kg/acre along with NPK. Split N into 3 doses: basal, knee-high, and tasseling.",
        "soil_notes": "Requires deep, fertile, well-drained soils; extremely sensitive to water stagnation.",
        "risk_factors": ["Fall Armyworm infestation", "Waterlogging at seedling stage", "Drought at silking stage"],
        "companion_crops": ["Soybean", "Cowpea", "Green gram"]
    },
    {
        "id": "pearl_millet",
        "name": "Pearl Millet (Bajra)",
        "hindi_name": "बाजरा (Bajra)",
        "scientific_name": "Pennisetum glaucum",
        "category": "Cereal",
        "suitable_soils": ["Sandy Loam Soil", "Red Soil", "Alluvial Soil"],
        "tolerated_soils": ["Laterite Soil"],
        "min_ph": 6.0,
        "max_ph": 8.5,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 8.0,
        "min_temp": 20.0,
        "max_temp": 42.0,
        "optimal_temp_min": 25.0,
        "optimal_temp_max": 35.0,
        "min_rainfall": 250.0,
        "max_rainfall": 600.0,
        "water_requirement": "Low",
        "seasons": ["Kharif", "Zaid"],
        "sowing_window": "June - July (Monsoon) or March (Summer)",
        "duration_days": "75 - 90 days",
        "estimated_yield_per_acre": "12 - 18 Quintals",
        "investment_level": "Low",
        "profit_potential": "Moderate",
        "ideal_n": 60.0,
        "ideal_p": 30.0,
        "ideal_k": 20.0,
        "sowing_tips": "Sow at 2-3 cm shallow depth. Highly drought-tolerant; excellent for arid/semi-arid regions.",
        "fertilizer_advice": "Modest fertility needs: 50% N + full P & K at sowing; remaining 50% N 30 days later.",
        "soil_notes": "Thrives even on nutrient-poor sandy and gravelly soils with good drainage.",
        "risk_factors": ["Ergot disease during rainy flowering", "Downy mildew in waterlogged soils"],
        "companion_crops": ["Cluster bean (Guar)", "Moth bean", "Cowpea"]
    },
    {
        "id": "sorghum",
        "name": "Sorghum (Jowar)",
        "hindi_name": "ज्वार (Jowar)",
        "scientific_name": "Sorghum bicolor",
        "category": "Cereal",
        "suitable_soils": ["Black Soil (Regur)", "Alluvial Soil", "Red Soil"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 5.8,
        "max_ph": 8.5,
        "optimal_ph_min": 6.2,
        "optimal_ph_max": 7.8,
        "min_temp": 18.0,
        "max_temp": 40.0,
        "optimal_temp_min": 24.0,
        "optimal_temp_max": 32.0,
        "min_rainfall": 350.0,
        "max_rainfall": 750.0,
        "water_requirement": "Low",
        "seasons": ["Kharif", "Rabi"],
        "sowing_window": "June - July (Kharif) or Sept - Oct (Rabi)",
        "duration_days": "95 - 115 days",
        "estimated_yield_per_acre": "14 - 20 Quintals",
        "investment_level": "Low",
        "profit_potential": "Moderate",
        "ideal_n": 80.0,
        "ideal_p": 40.0,
        "ideal_k": 30.0,
        "sowing_tips": "Sow behind plough at 3-4 cm depth. Excellent fodder value alongside grain harvest.",
        "fertilizer_advice": "Split nitrogen in 2 parts: 50% basal and 50% 35 days after sowing.",
        "soil_notes": "Heavy clay and black soils with good moisture retention produce superior results.",
        "risk_factors": ["Shoot fly at seedling stage", "Grain mold if rains occur at maturity"],
        "companion_crops": ["Pigeon pea (Arhar)", "Soybean"]
    },
    {
        "id": "finger_millet",
        "name": "Finger Millet (Ragi)",
        "hindi_name": "रागी (Mandua)",
        "scientific_name": "Eleusine coracana",
        "category": "Cereal",
        "suitable_soils": ["Red Soil", "Laterite Soil", "Sandy Loam Soil"],
        "tolerated_soils": ["Alluvial Soil"],
        "min_ph": 5.0,
        "max_ph": 7.5,
        "optimal_ph_min": 5.5,
        "optimal_ph_max": 7.0,
        "min_temp": 16.0,
        "max_temp": 35.0,
        "optimal_temp_min": 22.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 400.0,
        "max_rainfall": 900.0,
        "water_requirement": "Low",
        "seasons": ["Kharif"],
        "sowing_window": "June - August",
        "duration_days": "90 - 110 days",
        "estimated_yield_per_acre": "12 - 16 Quintals",
        "investment_level": "Low",
        "profit_potential": "Moderate to High (growing health demand)",
        "ideal_n": 50.0,
        "ideal_p": 30.0,
        "ideal_k": 25.0,
        "sowing_tips": "Transplanting 20-day-old seedlings yields 25% higher than direct broadcasting.",
        "fertilizer_advice": "Apply Farmyard Manure (FYM) @ 4 tonnes/acre plus modest chemical NPK.",
        "soil_notes": "Tolerates acidic red soils and hill slopes with moderate fertility.",
        "risk_factors": ["Blast disease in damp weather", "Bird damage at dough stage"],
        "companion_crops": ["Field bean (Avare)", "Niger", "Red gram"]
    },

    # ------------------ PULSES ------------------
    {
        "id": "chickpea",
        "name": "Chickpea (Gram / Chana)",
        "hindi_name": "चना (Chana)",
        "scientific_name": "Cicer arietinum",
        "category": "Pulse",
        "suitable_soils": ["Black Soil (Regur)", "Alluvial Soil", "Sandy Loam Soil"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 8.5,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.8,
        "min_temp": 10.0,
        "max_temp": 30.0,
        "optimal_temp_min": 15.0,
        "optimal_temp_max": 25.0,
        "min_rainfall": 250.0,
        "max_rainfall": 650.0,
        "water_requirement": "Low",
        "seasons": ["Rabi"],
        "sowing_window": "October 15th - November 15th",
        "duration_days": "95 - 120 days",
        "estimated_yield_per_acre": "8 - 12 Quintals",
        "investment_level": "Low to Moderate",
        "profit_potential": "High",
        "ideal_n": 20.0,  # Legume: fixes own N
        "ideal_p": 40.0,
        "ideal_k": 20.0,
        "sowing_tips": "Inoculate seeds with Rhizobium and PSB culture. Sow deep (7-10 cm) to utilize sub-soil moisture.",
        "fertilizer_advice": "Needs starter dose of 20 kg N; higher emphasis on Phosphorus (DAP or SSP) for root nodules.",
        "soil_notes": "Avoid waterlogged fields; requires loose, well-aerated deep soil.",
        "risk_factors": ["Helicoverpa (Pod borer)", "Fusarium wilt", "Excess rain during flowering"],
        "companion_crops": ["Mustard", "Barley", "Linseed"]
    },
    {
        "id": "pigeon_pea",
        "name": "Pigeon Pea (Arhar / Tur)",
        "hindi_name": "अरहर / तुअर (Tur)",
        "scientific_name": "Cajanus cajan",
        "category": "Pulse",
        "suitable_soils": ["Black Soil (Regur)", "Red Soil", "Alluvial Soil"],
        "tolerated_soils": ["Sandy Loam Soil"],
        "min_ph": 5.5,
        "max_ph": 8.0,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 18.0,
        "max_temp": 38.0,
        "optimal_temp_min": 22.0,
        "optimal_temp_max": 32.0,
        "min_rainfall": 500.0,
        "max_rainfall": 1000.0,
        "water_requirement": "Low to Medium",
        "seasons": ["Kharif"],
        "sowing_window": "June - July",
        "duration_days": "150 - 180 days (long duration) / 120 days (early)",
        "estimated_yield_per_acre": "8 - 14 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "High",
        "ideal_n": 25.0,
        "ideal_p": 50.0,
        "ideal_k": 25.0,
        "sowing_tips": "Deep taproot breaks hardpans. Excellent intercrop with Soybean or Cotton.",
        "fertilizer_advice": "Apply single super phosphate (SSP) for sulfur and phosphorus; seed treat with Rhizobium.",
        "soil_notes": "Deep loamy soils with good drainage; water stagnation over 48h causes root rot.",
        "risk_factors": ["Pod borer", "Sterility mosaic virus", "Excess moisture causing wilt"],
        "companion_crops": ["Soybean", "Cotton", "Sorghum"]
    },
    {
        "id": "green_gram",
        "name": "Green Gram (Moong)",
        "hindi_name": "मूंग (Moong)",
        "scientific_name": "Vigna radiata",
        "category": "Pulse",
        "suitable_soils": ["Alluvial Soil", "Red Soil", "Sandy Loam Soil", "Black Soil (Regur)"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 7.8,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 20.0,
        "max_temp": 40.0,
        "optimal_temp_min": 25.0,
        "optimal_temp_max": 35.0,
        "min_rainfall": 300.0,
        "max_rainfall": 600.0,
        "water_requirement": "Low",
        "seasons": ["Kharif", "Zaid"],
        "sowing_window": "June - July (Kharif) or March (Zaid/Summer)",
        "duration_days": "60 - 75 days (very short)",
        "estimated_yield_per_acre": "5 - 8 Quintals",
        "investment_level": "Low",
        "profit_potential": "High (quick turnaround cash crop)",
        "ideal_n": 15.0,
        "ideal_p": 35.0,
        "ideal_k": 15.0,
        "sowing_tips": "Ideal catch-crop between wheat harvest and paddy transplanting. Enriches soil with 30-40 kg N/ha.",
        "fertilizer_advice": "Seed inoculation with Rhizobium + 100 kg SSP/acre at sowing.",
        "soil_notes": "Light to medium textured fertile loams; intolerant to salinity and waterlogging.",
        "risk_factors": ["Yellow Mosaic Virus (YMV) carried by whitefly", "Unseasonal rain at pod maturity"],
        "companion_crops": ["Maize", "Sugarcane intercrop", "Sunflower"]
    },
    {
        "id": "black_gram",
        "name": "Black Gram (Urad)",
        "hindi_name": "उड़द (Urad)",
        "scientific_name": "Vigna mungo",
        "category": "Pulse",
        "suitable_soils": ["Black Soil (Regur)", "Alluvial Soil", "Red Soil"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 8.0,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 20.0,
        "max_temp": 38.0,
        "optimal_temp_min": 25.0,
        "optimal_temp_max": 33.0,
        "min_rainfall": 400.0,
        "max_rainfall": 750.0,
        "water_requirement": "Low to Medium",
        "seasons": ["Kharif", "Zaid"],
        "sowing_window": "June - July or February - March",
        "duration_days": "70 - 85 days",
        "estimated_yield_per_acre": "6 - 9 Quintals",
        "investment_level": "Low",
        "profit_potential": "High",
        "ideal_n": 15.0,
        "ideal_p": 35.0,
        "ideal_k": 15.0,
        "sowing_tips": "Seed treatment with Trichoderma (5g/kg) and Rhizobium. Compact seedbed helps uniform germination.",
        "fertilizer_advice": "Apply starter nitrogen and phosphorus as basal dose. Spray 2% urea at pod filling for yield boost.",
        "soil_notes": "Deep retentive soils like regur/black cotton soils are prime.",
        "risk_factors": ["Powdery mildew", "Whitefly transmitted YMV", "Water stagnation"],
        "companion_crops": ["Cotton", "Sorghum", "Pigeon pea"]
    },
    {
        "id": "lentil",
        "name": "Lentil (Masoor)",
        "hindi_name": "मसूर (Masoor)",
        "scientific_name": "Lens culinaris",
        "category": "Pulse",
        "suitable_soils": ["Alluvial Soil", "Clay Loam Soil", "Black Soil (Regur)"],
        "tolerated_soils": ["Sandy Loam Soil"],
        "min_ph": 5.8,
        "max_ph": 8.0,
        "optimal_ph_min": 6.0,
        "optimal_ph_max": 7.5,
        "min_temp": 10.0,
        "max_temp": 26.0,
        "optimal_temp_min": 14.0,
        "optimal_temp_max": 22.0,
        "min_rainfall": 250.0,
        "max_rainfall": 600.0,
        "water_requirement": "Low",
        "seasons": ["Rabi"],
        "sowing_window": "Late October - November",
        "duration_days": "110 - 130 days",
        "estimated_yield_per_acre": "7 - 10 Quintals",
        "investment_level": "Low",
        "profit_potential": "Moderate to High",
        "ideal_n": 15.0,
        "ideal_p": 35.0,
        "ideal_k": 20.0,
        "sowing_tips": "Can be grown as a relay crop (Utera / Paira) in standing rice fields before harvest.",
        "fertilizer_advice": "Phosphorus is the driving element: 30-40 kg P2O5 per hectare.",
        "soil_notes": "Well-drained loam or alluvial silt; sensitive to severe cold during early seedling phase.",
        "risk_factors": ["Rust", "Wilt", "Aphids during flowering"],
        "companion_crops": ["Barley", "Mustard"]
    },

    # ------------------ OILSEEDS ------------------
    {
        "id": "mustard",
        "name": "Mustard / Rapeseed (Sarson)",
        "hindi_name": "सरसों / राई (Sarson)",
        "scientific_name": "Brassica juncea",
        "category": "Oilseed",
        "suitable_soils": ["Alluvial Soil", "Sandy Loam Soil", "Red Soil"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 8.2,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 10.0,
        "max_temp": 28.0,
        "optimal_temp_min": 14.0,
        "optimal_temp_max": 22.0,
        "min_rainfall": 250.0,
        "max_rainfall": 500.0,
        "water_requirement": "Low to Medium",
        "seasons": ["Rabi"],
        "sowing_window": "September 25th - October 20th",
        "duration_days": "100 - 125 days",
        "estimated_yield_per_acre": "8 - 12 Quintals",
        "investment_level": "Low",
        "profit_potential": "High",
        "ideal_n": 80.0,
        "ideal_p": 40.0,
        "ideal_k": 30.0,
        "sowing_tips": "Requires fine firm seedbed. Sow seeds at 2-3 cm depth; thin seedlings at 15-20 days.",
        "fertilizer_advice": "Crucial requirement: Apply 20 kg/ha elemental Sulfur or gypsum for high oil content.",
        "soil_notes": "Light to medium alluvial and sandy loam soils with adequate winter sub-moisture.",
        "risk_factors": ["Aphid (Mahun) attack during foggy cloudy weather", "Alternaria blight", "White rust"],
        "companion_crops": ["Wheat (intercrop)", "Gram", "Potato"]
    },
    {
        "id": "soybean",
        "name": "Soybean",
        "hindi_name": "सोयाबीन (Soybean)",
        "scientific_name": "Glycine max",
        "category": "Oilseed",
        "suitable_soils": ["Black Soil (Regur)", "Alluvial Soil", "Clay Loam Soil"],
        "tolerated_soils": ["Red Soil"],
        "min_ph": 6.0,
        "max_ph": 7.8,
        "optimal_ph_min": 6.3,
        "optimal_ph_max": 7.2,
        "min_temp": 18.0,
        "max_temp": 35.0,
        "optimal_temp_min": 22.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 600.0,
        "max_rainfall": 1000.0,
        "water_requirement": "Medium",
        "seasons": ["Kharif"],
        "sowing_window": "June 15th - July 10th (after 75-100mm initial rains)",
        "duration_days": "90 - 110 days",
        "estimated_yield_per_acre": "10 - 15 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "High",
        "ideal_n": 30.0,
        "ideal_p": 60.0,
        "ideal_k": 30.0,
        "sowing_tips": "Bradyrhizobium japonicum seed inoculation is mandatory for maximum nodulation.",
        "fertilizer_advice": "Basal application of 20kg N, 60kg P2O5, 20kg K2O, and 20kg Sulfur per hectare.",
        "soil_notes": "Deep black soils with high organic matter produce record yields; avoid waterlogging.",
        "risk_factors": ["Girdle beetle", "Yellow mosaic virus", "Drought during pod filling"],
        "companion_crops": ["Pigeon pea (Tur)", "Maize", "Cotton"]
    },
    {
        "id": "groundnut",
        "name": "Groundnut (Peanut)",
        "hindi_name": "मूंगफली (Mungfali)",
        "scientific_name": "Arachis hypogaea",
        "category": "Oilseed",
        "suitable_soils": ["Sandy Loam Soil", "Red Soil", "Alluvial Soil"],
        "tolerated_soils": ["Black Soil (Regur)"],
        "min_ph": 5.8,
        "max_ph": 7.8,
        "optimal_ph_min": 6.2,
        "optimal_ph_max": 7.2,
        "min_temp": 20.0,
        "max_temp": 36.0,
        "optimal_temp_min": 24.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 450.0,
        "max_rainfall": 800.0,
        "water_requirement": "Low to Medium",
        "seasons": ["Kharif", "Zaid"],
        "sowing_window": "June - July (Kharif) or Jan - Feb (Summer)",
        "duration_days": "105 - 125 days",
        "estimated_yield_per_acre": "10 - 16 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "High",
        "ideal_n": 20.0,
        "ideal_p": 40.0,
        "ideal_k": 40.0,
        "sowing_tips": "Loose friable soil is essential so pegs (gynophores) can penetrate underground effortlessly.",
        "fertilizer_advice": "Apply Gypsum @ 200kg/acre at flowering/pegging stage for pod filling and kernel weight.",
        "soil_notes": "Sandy loam and friable red loam are ideal; heavy clays hinder pod harvesting.",
        "risk_factors": ["Tikka leaf spot", "White grub", "Collar rot during damp spells"],
        "companion_crops": ["Pearl millet (Bajra)", "Pigeon pea", "Sunflower"]
    },
    {
        "id": "sunflower",
        "name": "Sunflower",
        "hindi_name": "सूरजमुखी (Surajmukhi)",
        "scientific_name": "Helianthus annuus",
        "category": "Oilseed",
        "suitable_soils": ["Black Soil (Regur)", "Alluvial Soil", "Red Soil"],
        "tolerated_soils": ["Sandy Loam Soil", "Clay Loam Soil"],
        "min_ph": 6.2,
        "max_ph": 8.0,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 16.0,
        "max_temp": 38.0,
        "optimal_temp_min": 20.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 350.0,
        "max_rainfall": 700.0,
        "water_requirement": "Low to Medium",
        "seasons": ["Kharif", "Rabi", "Zaid"],
        "sowing_window": "Photo-insensitive: Can be sown year-round with irrigation",
        "duration_days": "80 - 100 days",
        "estimated_yield_per_acre": "8 - 12 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "Moderate to High",
        "ideal_n": 60.0,
        "ideal_p": 60.0,
        "ideal_k": 30.0,
        "sowing_tips": "Maintain 45x30 cm spacing. Hand pollination or beehives enhance seed setting significantly.",
        "fertilizer_advice": "Boron application (0.2% spray) at ray-floret stage prevents hollow/chaffy seeds.",
        "soil_notes": "Adaptable to diverse soils, but black and deep loams maximize seed oil percentage.",
        "risk_factors": ["Parrot/bird menace near harvest", "Head rot during wet spells"],
        "companion_crops": ["Groundnut", "Pigeon pea"]
    },

    # ------------------ FIBER & CASH CROPS ------------------
    {
        "id": "cotton",
        "name": "Cotton (White Gold)",
        "hindi_name": "कपास (Kapas)",
        "scientific_name": "Gossypium hirsutum",
        "category": "Fiber",
        "suitable_soils": ["Black Soil (Regur)", "Alluvial Soil"],
        "tolerated_soils": ["Red Soil"],
        "min_ph": 6.2,
        "max_ph": 8.5,
        "optimal_ph_min": 6.8,
        "optimal_ph_max": 8.0,
        "min_temp": 20.0,
        "max_temp": 42.0,
        "optimal_temp_min": 24.0,
        "optimal_temp_max": 34.0,
        "min_rainfall": 500.0,
        "max_rainfall": 1100.0,
        "water_requirement": "Medium to High",
        "seasons": ["Kharif"],
        "sowing_window": "April - May (Irrigated) or June - July (Rainfed)",
        "duration_days": "150 - 180 days",
        "estimated_yield_per_acre": "10 - 16 Quintals (seed cotton)",
        "investment_level": "High",
        "profit_potential": "Very High",
        "ideal_n": 120.0,
        "ideal_p": 60.0,
        "ideal_k": 60.0,
        "sowing_tips": "Maintain 90x60 cm or 120x45 cm spacing. Monitor for sucking pests in first 60 days.",
        "fertilizer_advice": "Apply N in 3-4 splits (basal, square formation, flowering, and boll development).",
        "soil_notes": "Deep black cotton soils with excellent moisture holding capacity are unmatched.",
        "risk_factors": ["Pink bollworm", "Sucking pests (thrips, jassids)", "Unseasonal rain during boll bursting"],
        "companion_crops": ["Okra / Bhindi (trap crop)", "Marigold", "Cowpea"]
    },
    {
        "id": "sugarcane",
        "name": "Sugarcane",
        "hindi_name": "गन्ना (Ganna)",
        "scientific_name": "Saccharum officinarum",
        "category": "Cash Crop",
        "suitable_soils": ["Clay Loam Soil", "Alluvial Soil", "Black Soil (Regur)"],
        "tolerated_soils": ["Red Soil"],
        "min_ph": 6.0,
        "max_ph": 8.2,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.8,
        "min_temp": 20.0,
        "max_temp": 38.0,
        "optimal_temp_min": 25.0,
        "optimal_temp_max": 33.0,
        "min_rainfall": 1200.0,
        "max_rainfall": 2200.0,
        "water_requirement": "High",
        "seasons": ["All Season / Flexible"],
        "sowing_window": "Autumn (Oct - Nov) or Spring (Feb - March)",
        "duration_days": "300 - 360 days (annual crop)",
        "estimated_yield_per_acre": "300 - 450 Quintals",
        "investment_level": "High",
        "profit_potential": "Very High (assured sugar mill procurement)",
        "ideal_n": 150.0,
        "ideal_p": 80.0,
        "ideal_k": 90.0,
        "sowing_tips": "Use two-budded setts treated with Trichoderma. Trench planting saves 30% water and prevents lodging.",
        "fertilizer_advice": "Heavy feeder: 250kg N, 80kg P, 100kg K per hectare split across grand growth periods.",
        "soil_notes": "Requires deep well-drained loams/clays with abundant organic carbon; strictly needs assured irrigation.",
        "risk_factors": ["Red rot disease", "Early shoot borer", "Water stress during summer tillering"],
        "companion_crops": ["Potato (in autumn cane)", "Onion", "Moong"]
    },
    {
        "id": "jute",
        "name": "Jute (Golden Fiber)",
        "hindi_name": "पटसन / जूट (Jute)",
        "scientific_name": "Corchorus olitorius",
        "category": "Fiber",
        "suitable_soils": ["Alluvial Soil", "Clay Loam Soil"],
        "tolerated_soils": ["Sandy Loam Soil"],
        "min_ph": 5.8,
        "max_ph": 7.5,
        "optimal_ph_min": 6.2,
        "optimal_ph_max": 7.0,
        "min_temp": 24.0,
        "max_temp": 38.0,
        "optimal_temp_min": 26.0,
        "optimal_temp_max": 35.0,
        "min_rainfall": 1200.0,
        "max_rainfall": 2000.0,
        "water_requirement": "High",
        "seasons": ["Kharif", "Zaid"],
        "sowing_window": "March - May (Pre-monsoon)",
        "duration_days": "120 - 140 days",
        "estimated_yield_per_acre": "12 - 16 Quintals (dry fiber)",
        "investment_level": "Moderate",
        "profit_potential": "Moderate to High",
        "ideal_n": 60.0,
        "ideal_p": 30.0,
        "ideal_k": 30.0,
        "sowing_tips": "Requires high humidity (>70%) and warm humid climate. Water retting access needed post-harvest.",
        "fertilizer_advice": "Balanced NPK; excess nitrogen causes stem lodging and lowers fiber tensile strength.",
        "soil_notes": "Rich river alluvium, flood-plain silt soils, and clay loams.",
        "risk_factors": ["Stem rot", "Semilooper caterpillar", "Scarcity of clean retting water"],
        "companion_crops": ["Paddy (in rotation)"]
    },

    # ------------------ VEGETABLES & SPICES ------------------
    {
        "id": "tomato",
        "name": "Tomato",
        "hindi_name": "टमाटर (Tamatar)",
        "scientific_name": "Solanum lycopersicum",
        "category": "Vegetable",
        "suitable_soils": ["Sandy Loam Soil", "Red Soil", "Alluvial Soil"],
        "tolerated_soils": ["Black Soil (Regur)"],
        "min_ph": 5.8,
        "max_ph": 7.5,
        "optimal_ph_min": 6.0,
        "optimal_ph_max": 7.0,
        "min_temp": 15.0,
        "max_temp": 35.0,
        "optimal_temp_min": 18.0,
        "optimal_temp_max": 28.0,
        "min_rainfall": 400.0,
        "max_rainfall": 900.0,
        "water_requirement": "Medium",
        "seasons": ["Kharif", "Rabi", "Zaid"],
        "sowing_window": "July - Aug (Kharif) or Oct - Nov (Rabi) or Feb (Summer)",
        "duration_days": "90 - 130 days",
        "estimated_yield_per_acre": "150 - 250 Quintals",
        "investment_level": "Moderate to High",
        "profit_potential": "High (volatile market returns)",
        "ideal_n": 100.0,
        "ideal_p": 60.0,
        "ideal_k": 80.0,
        "sowing_tips": "Transplant 25-day sturdy nursery seedlings on raised beds with drip irrigation and staking.",
        "fertilizer_advice": "High Potassium feeder for firm skin, bright red lycopene color, and long shelf life.",
        "soil_notes": "Deep, well-aerated sandy loam with excellent organic matter; highly prone to bacterial wilt in waterlogging.",
        "risk_factors": ["Early & Late Blight", "Tomato leaf curl virus", "Fruit borer", "Price volatility"],
        "companion_crops": ["Marigold (repels nematodes)", "Basil", "Garlic"]
    },
    {
        "id": "potato",
        "name": "Potato",
        "hindi_name": "आलू (Aloo)",
        "scientific_name": "Solanum tuberosum",
        "category": "Vegetable",
        "suitable_soils": ["Sandy Loam Soil", "Alluvial Soil"],
        "tolerated_soils": ["Red Soil"],
        "min_ph": 5.2,
        "max_ph": 7.2,
        "optimal_ph_min": 5.5,
        "optimal_ph_max": 6.5,
        "min_temp": 12.0,
        "max_temp": 26.0,
        "optimal_temp_min": 15.0,
        "optimal_temp_max": 20.0,
        "min_rainfall": 300.0,
        "max_rainfall": 600.0,
        "water_requirement": "Medium",
        "seasons": ["Rabi"],
        "sowing_window": "October 15th - November 10th",
        "duration_days": "80 - 105 days",
        "estimated_yield_per_acre": "100 - 160 Quintals",
        "investment_level": "High (seed tuber costs)",
        "profit_potential": "High",
        "ideal_n": 120.0,
        "ideal_p": 60.0,
        "ideal_k": 100.0,
        "sowing_tips": "Use certified seed tubers with 2-3 active eyes. Earth up ridges twice to prevent tuber greening.",
        "fertilizer_advice": "MOP (Muriate of Potash) or SOP (Sulfate of Potash) is crucial for tuber bulking and starch.",
        "soil_notes": "Loose, friable sandy loam rich in humus; tubers cannot expand in hard compact clay.",
        "risk_factors": ["Late blight epidemic during cloudy damp weather", "Aphids spreading viruses"],
        "companion_crops": ["Mustard", "Radish", "Onion"]
    },
    {
        "id": "onion",
        "name": "Onion",
        "hindi_name": "प्याज़ (Pyaz)",
        "scientific_name": "Allium cepa",
        "category": "Vegetable",
        "suitable_soils": ["Sandy Loam Soil", "Alluvial Soil", "Red Soil"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 7.8,
        "optimal_ph_min": 6.2,
        "optimal_ph_max": 7.2,
        "min_temp": 13.0,
        "max_temp": 32.0,
        "optimal_temp_min": 16.0,
        "optimal_temp_max": 25.0,
        "min_rainfall": 350.0,
        "max_rainfall": 700.0,
        "water_requirement": "Medium",
        "seasons": ["Kharif", "Rabi"],
        "sowing_window": "Oct - Nov (Rabi / Main crop) or May - June (Kharif)",
        "duration_days": "120 - 140 days",
        "estimated_yield_per_acre": "100 - 150 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "High (lucrative commercial crop)",
        "ideal_n": 100.0,
        "ideal_p": 50.0,
        "ideal_k": 60.0,
        "sowing_tips": "Shallow rooted crop: transplant seedlings 10x10 cm apart. Stop irrigation 15 days before harvest to cure skins.",
        "fertilizer_advice": "Sulfur application (30kg/ha) increases pungency, bulb firmness, and storage quality.",
        "soil_notes": "Friable, fertile loamy soil with neutral pH; heavy clays produce deformed split bulbs.",
        "risk_factors": ["Thrips", "Purple blotch", "Premature bolting if hit by cold spells"],
        "companion_crops": ["Cabbage", "Carrot", "Beetroot"]
    },
    {
        "id": "chilli",
        "name": "Chilli / Red Pepper",
        "hindi_name": "मिर्च (Mirch)",
        "scientific_name": "Capsicum annuum",
        "category": "Spices",
        "suitable_soils": ["Black Soil (Regur)", "Red Soil", "Sandy Loam Soil", "Alluvial Soil"],
        "tolerated_soils": ["Clay Loam Soil"],
        "min_ph": 6.0,
        "max_ph": 7.8,
        "optimal_ph_min": 6.5,
        "optimal_ph_max": 7.5,
        "min_temp": 16.0,
        "max_temp": 38.0,
        "optimal_temp_min": 20.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 400.0,
        "max_rainfall": 900.0,
        "water_requirement": "Medium",
        "seasons": ["Kharif", "Rabi"],
        "sowing_window": "June - July or Oct - Nov",
        "duration_days": "120 - 160 days (multiple pickings)",
        "estimated_yield_per_acre": "25 - 40 Quintals (green) / 8 - 14 Quintals (dry red)",
        "investment_level": "Moderate to High",
        "profit_potential": "Very High",
        "ideal_n": 100.0,
        "ideal_p": 50.0,
        "ideal_k": 50.0,
        "sowing_tips": "Raise on nursery beds; treat with Imidacloprid for sucking pests; transplant at 60x45 cm.",
        "fertilizer_advice": "Split nitrogen application at 30, 60, and 90 days after transplanting.",
        "soil_notes": "Well-drained loam or black soil; water stagnation even for 24 hours causes wilt and leaf shedding.",
        "risk_factors": ["Chilli leaf curl virus", "Thrips & Mites (murda disease)", "Anthracnose fruit rot"],
        "companion_crops": ["Marigold (trap crop for thrips and nematodes)", "Onion"]
    },
    {
        "id": "turmeric",
        "name": "Turmeric",
        "hindi_name": "हल्दी (Haldi)",
        "scientific_name": "Curcuma longa",
        "category": "Spices",
        "suitable_soils": ["Red Soil", "Alluvial Soil", "Clay Loam Soil"],
        "tolerated_soils": ["Black Soil (Regur)", "Sandy Loam Soil"],
        "min_ph": 5.5,
        "max_ph": 7.5,
        "optimal_ph_min": 6.0,
        "optimal_ph_max": 7.0,
        "min_temp": 20.0,
        "max_temp": 35.0,
        "optimal_temp_min": 22.0,
        "optimal_temp_max": 30.0,
        "min_rainfall": 1000.0,
        "max_rainfall": 2000.0,
        "water_requirement": "Medium to High",
        "seasons": ["Kharif"],
        "sowing_window": "May - June (Pre-monsoon)",
        "duration_days": "210 - 260 days (8 - 9 months)",
        "estimated_yield_per_acre": "80 - 120 Quintals (fresh rhizomes)",
        "investment_level": "High (rhizome seed cost)",
        "profit_potential": "Very High",
        "ideal_n": 120.0,
        "ideal_p": 60.0,
        "ideal_k": 100.0,
        "sowing_tips": "Plant mother or finger rhizomes on raised beds. Mulch generously with green leaves (4 tonnes/acre).",
        "fertilizer_advice": "Heavy feeder of organic manure: 10 tonnes FYM/acre + Potash split at 45 and 90 days.",
        "soil_notes": "Warm, humid climate and well-drained fertile friable loamy soil.",
        "risk_factors": ["Rhizome rot in waterlogged conditions", "Leaf spot"],
        "companion_crops": ["Maize or Arhar as partial shade border crop", "Chilli"]
    },
    {
        "id": "watermelon",
        "name": "Watermelon",
        "hindi_name": "तरबूज (Tarbooj)",
        "scientific_name": "Citrullus lanatus",
        "category": "Vegetable",
        "suitable_soils": ["Sandy Loam Soil", "Alluvial Soil"],
        "tolerated_soils": ["Red Soil"],
        "min_ph": 6.0,
        "max_ph": 7.5,
        "optimal_ph_min": 6.2,
        "optimal_ph_max": 7.0,
        "min_temp": 22.0,
        "max_temp": 40.0,
        "optimal_temp_min": 25.0,
        "optimal_temp_max": 35.0,
        "min_rainfall": 200.0,
        "max_rainfall": 500.0,
        "water_requirement": "Medium (requires dry ripening period)",
        "seasons": ["Zaid"],
        "sowing_window": "January - March (Summer)",
        "duration_days": "80 - 95 days",
        "estimated_yield_per_acre": "120 - 200 Quintals",
        "investment_level": "Moderate",
        "profit_potential": "High (quick summer returns)",
        "ideal_n": 80.0,
        "ideal_p": 50.0,
        "ideal_k": 70.0,
        "sowing_tips": "Sow in pits or riverbeds with channel irrigation. Drip fertigation with silver-black mulch doubles yield.",
        "fertilizer_advice": "Boost Potassium during fruit sizing for high TSS (sweetness) and thick rind transportability.",
        "soil_notes": "Warm, sandy or sandy loam soils that heat up quickly; riverine diara land is traditional.",
        "risk_factors": ["Powdery and Downy Mildew", "Fruit fly", "Sudden rain during ripening bursts fruit"],
        "companion_crops": ["Muskmelon", "Bottle gourd"]
    }
]

def get_all_crops() -> List[Dict[str, Any]]:
    return CROPS_DATABASE

def get_crop_by_id(crop_id: str) -> Dict[str, Any]:
    for crop in CROPS_DATABASE:
        if crop["id"].lower() == crop_id.lower():
            return crop
    return None
